#!/bin/bash
#gurkulcn1="192.168.1.10"
#gurkulcn2="192.168.1.11"
nodes="cn1 cn2"
myname=`hostname`

#import VM and LABS information
# VM groups
rhel61='cn1.gurkulrhel6161  cn1.gurkulrhel6162'
rhel62='cn1.gurkulrhel6163  cn1.gurkulrhel6164'
rhel63='cn1.gurkulrhel6165  cn1.gurkulrhel6166'
rhel64='cn1.gurkulrhel6167  cn1.gurkulrhel6168'
rhel65='cn1.gurkulrhel6169  cn1.gurkulrhel6170'
rhel66='cn2.gurkulrhel6171  cn2.gurkulrhel6172'
rhel67='cn2.gurkulrhel6173  cn2.gurkulrhel6174'
rhel68='cn2.gurkulrhel6175  cn2.gurkulrhel6176'
rhel69='cn2.gurkulrhel6177  cn2.gurkulrhel6178'
rhel610='cn2.gurkulrhel6179  cn2.gurkulrhel6180'
rhel71='cn1.gurkulrhel7070  cn1.gurkulrhel7071'
rhel72='cn1.gurkulrhel7072  cn1.gurkulrhel7073'
rhel73='cn1.gurkulrhel7074  cn1.gurkulrhel7075'
rhel74='cn1.gurkulrhel7076  cn1.gurkulrhel7077'
rhel75='cn1.gurkulrhel7078  cn1.gurkulrhel7079'
rhel76='cn2.gurkulrhel7080  cn2.gurkulrhel7081'
rhel77='cn2.gurkulrhel7082  cn2.gurkulrhel7083'
rhel78='cn2.gurkulrhel7084  cn2.gurkulrhel7085'
rhel79='cn2.gurkulrhel7086  cn2.gurkulrhel7087'
rhel710='cn2.gurkulrhel7088  cn2.gurkulrhel7089'
sol1='cn1.gurkulsol10101  cn1.gurkulsol10111'
sol2='cn1.gurkulsol10102  cn1.gurkulsol10112'
sol3='cn1.gurkulsol10103  cn1.gurkulsol10113'
sol4='cn1.gurkulsol10104  cn1.gurkulsol10114'
sol5='cn1.gurkulsol10105  cn1.gurkulsol10115'
sol6='cn1.gurkulsol10106  cn1.gurkulsol10116'
sol7='cn1.gurkulsol10107  cn1.gurkulsol10117'
sol8='cn2.gurkulsol10121  cn2.gurkulsol10131'
sol9='cn2.gurkulsol10122  cn2.gurkulsol10132'
sol10='cn2.gurkulsol10123  cn2.gurkulsol10133'
sol11='cn2.gurkulsol10124  cn2.gurkulsol10134'
sol12='cn2.gurkulsol10125  cn2.gurkulsol10135'
sol13='cn2.gurkulsol10126  cn2.gurkulsol10136'
sol14='cn2.gurkulsol10127  cn2.gurkulsol10137'
# labcode to grooup matching. any means any available group
SOL1='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL2='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL3='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL4='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL5='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL6='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL7='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL8='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL9='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL10='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL11='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL12='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL13='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL14='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL15='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL16='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL17='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL18='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL19='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
SOL20='sol1 sol2 sol3 sol4 sol5 sol6 sol7 sol8 sol9 sol10 sol11 sol12 '
RHEL61='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL62='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL63='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL64='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL65='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL66='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL67='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL68='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL69='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL610='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL611='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL612='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL613='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL614='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL615='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL616='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL617='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL618='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL619='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL620='rhel61 rhel62 rhel63 rhel64 rhel65 rhel66 rhel67 rhel68 rhel69 rhel610 '
RHEL71='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL72='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL73='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL74='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL75='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL76='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL77='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL78='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL79='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL710='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL711='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL712='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL713='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL714='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL715='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL716='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL717='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL718='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL719='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '
RHEL720='rhel71 rhel72 rhel73 rhel74 rhel75 rhel76 rhel77 rhel78 rhel79 rhel710 '


rqcache="/home/requests/cache"
tstate=""
for vm in `vboxmanage list vms|awk '{print $1}'|sed -e 's/"//g'`; do 
state=`vboxmanage showvminfo $vm | grep -i State|awk '{print $2}'|sed -e 's\powered\off\g'`
tstate="$tstate $vm:$state" 
done


#for cn in $nodes ; do
#for vm in `ssh root@gurkul-${cn} "vboxmanage list vms"|awk '{print $1}'|sed -e 's/"//g'`; do 
#state=`ssh root@gurkul-${cn} "vboxmanage showvminfo $vm --machinereadable"|grep -i VMState=|awk -F= '{print $2}'`
	echo $vm $state >> vmstate.$$
#done  
#done

for rq in `ls $rqcache/*active*`;do
trq=`echo $rq|sed -e 's/active/inprocess/'`
crq=`echo $rq|sed -e 's/active/complete/'`
rqtime=`echo $rq|awk -F'.' '{print $1}'`
labcode=`echo $rq|awk -F'.' '{print $2}'`
user=`echo $rq|awk -F'.' '{print $3}'`
tcn=`echo $rq|awk -F'.' '{print $4}'`
    if [[ $myname == $tcn ]]; then
	mv $rq $trq

	for vmgroup in ${!labcode};
	do
	vm1=`echo ${!vmgroup}|awk '{print $1}'`
	vm2=`echo ${!vmgroup}|awk '{print $2}'`
	if `echo $tstate|grep "$vm1:off" && `echo $tstate|grep "$vm2:off"; then
	  echo "Restoring BASIC configuration" > $trq
	  if `VBoxManage snapshot $vm1 restore BASE >> $trq` && `VBoxManage snapshot $vm2 restore BASE >> $trq`; then
		if `vboxmanage startvm $vm1 --type headless > $trq` && `vboxmanage startvm $vm2 --type headless >> $trq`; then
		vm1port=`vboxmanage showvminfo $vm1|grep "VRDE property: TCP/Ports  ="|sed -e 's/VRDE.*=//g' `
		vm2port=`vboxmanage showvminfo $vm2|grep "VRDE property: TCP/Ports  ="|sed -e 's/VRDE.*=//g' `
		echo "your lab access details" > $crq
		echo "Please access $vm1  console port:$vm1port" >> $crq
		echo "Please access $vm2  console port:$vm2port" >> $crq
	  	fi
	  fi
	  break
	else 
	  continue
	fi
	done
   	if  [[ $myname == $tcn ]] && [[ -f $crq ]]; then 
	   echo "Your VM information available in the file $crq"
	   elif [[ $myname == $tcn ]] && [[ ! -f $crq ]]; then
	   echo "$rq : Failed"
	fi
   fi
done

